---
# yaml-language-server: $schema=../../../../schemas/values.json
cilium:
  autoDirectNodeRoutes: false
  bandwidthManager:
    enabled: true
    bbr: true
  bgpControlPlane:
    enabled: false
  bpf:
    datapathMode: netkit
    masquerade: true
    preallocateMaps: true
  bpfClockProbe: true
  cgroup:
    autoMount:
      enabled: false
    hostRoot: /sys/fs/cgroup
  cluster:
    id: 1
    name: kubernetes
  cni:
    exclusive: false  # for multus
  dashboards:
    enabled: false  # @todo
  enableIPv4BIGTCP: false
  # enableRuntimeDeviceDetection: true
  endpointRoutes:
    enabled: true
  envoy:
    rollOutPods: true
    prometheus:
      serviceMonitor:
        enabled: true
    resources:
      requests:
        cpu: "50m"
        memory: "32Mi"
      limits:
        memory: "1Gi"
  hubble:
    enabled: true
    metrics:
      enabled:
        - dns:query
        - drop
        - tcp
        - flow
        - port-distribution
        - icmp
        - http
      # dashboards:  # @todo: grafana
      #   enabled: true
      serviceMonitor:
        enabled: true
    relay:
      enabled: true
      rollOutPods: true
      prometheus:
        serviceMonitor:
          enabled: true
    ui:
      enabled: true
      rollOutPods: true
  ipam:
    mode: kubernetes
  ipv4NativeRoutingCIDR: 172.30.0.0/16
  k8sServiceHost: 127.0.0.1
  k8sServicePort: 7445
  kubeProxyReplacement: true
  kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
  l2announcements:
    enabled: true
  loadBalancer:
    algorithm: maglev
    mode: dsr
  localRedirectPolicy: true
  operator:
    enabled: true
    dashboards:
      enabled: false  # @todo grafana dashboards
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
    replicas: 2
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        memory: "1Gi"
    rollOutPods: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
      trustCRDsExist: true
  resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      memory: "2Gi"
  rollOutCiliumPods: true
  routingMode: native
  securityContext:
    capabilities:
      ciliumAgent:
        - BPF
        - CHOWN
        - DAC_OVERRIDE
        - FOWNER
        - IPC_LOCK
        - KILL
        - NET_ADMIN
        - NET_RAW
        - PERFMON
        - SETGID
        - SETUID
        - SYS_ADMIN
        - SYS_RESOURCE
      cleanCiliumState:
        - NET_ADMIN
        - SYS_ADMIN
        - SYS_RESOURCE
  tls:  # this whole section is set only to remove `cilium-secrets` namespace
    readSecretsOnlyFromSecretsNamespace: false
    secretsNamespace:
      create: false
    secretSync:
      enabled: false
  tunnelProtocol: ""
