---
# yaml-language-server: $schema=../../../../schemas/cluster-values.json
applications:
  cilium:
    namespace: kube-system
    path: kubernetes/apps/kube-system/cilium
    psp: privileged
    ignoreDifferences: |
      - kind: Secret
        group: ""
        name: cilium-ca
        jsonPointers:
          - "/data"
      - kind: Secret
        group: ""
        name: hubble-relay-client-certs
        jsonPointers:
          - "/data"
      - kind: Secret
        group: ""
        name: hubble-server-certs
        jsonPointers:
          - "/data"
    helmValues: |
      cilium:
        bgpControlPlane:
          enabled: true
        cluster:
          name: deedee
      pools:
        - 10.42.20.0/24
