---
coredns:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
  deployment:
    annotations:
      reloader.stakater.com/auto: "true"
  fullnameOverride: coredns
  image:
    repository: mirror.gcr.io/coredns/coredns
  k8sAppLabelOverride: kube-dns
  replicaCount: 2
  securityContext:
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
  servers:
    - zones:
        - zone: .
          scheme: dns://
          use_tcp: true
      port: 53
      plugins:
        - name: errors
        - name: health
          configBlock: |-
            lameduck 5s
        - name: ready
        - name: log
          configBlock: |-
            class error
        - name: prometheus
          parameters: 0.0.0.0:9153
        - name: kubernetes
          parameters: cluster.local in-addr.arpa ip6.arpa
          configBlock: |-
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
        - name: forward
          parameters: ". /etc/resolv.conf"
        - name: cache
          parameters: 30
        - name: loop
        - name: reload
        - name: loadbalance
  service:
    name: kube-dns
    clusterIP: 172.31.0.10
  serviceAccount:
    create: true
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
