---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/ajgon/home-test.git
    targetRevision: master
    path: kubernetes/clusters/meemee
    helm:
      valueFiles:
        - values/argo-cd.yaml
        - values/cilium.yaml
        - values/coredns.yaml
        - values/external-secrets.yaml
        - values/metrics-server.yaml
        # waiting for: https://github.com/sigstore/policy-controller/pull/1725
        # - values/policy-controller.yaml
        - values/spegel.yaml
  ignoreDifferences:
    - group: "argoproj.io"
      kind: Application
      jsonPointers:
        - "/spec/ignoreDifferences"
