---
# yaml-language-server: $schema=https://deedee-ops.github.io/schemas/argoproj.io/application_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spegel
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: ghcr.io/spegel-org/helm-charts
      chart: spegel
      targetRevision: 0.1.1
      helm:
        values: |
          spegel:
            appendMirrors: true
            containerdSock: /run/containerd/containerd.sock
            containerdRegistryConfigPath: /etc/cri/conf.d/hosts
          service:
            registry:
              hostPort: 29999
          serviceMonitor:
            enabled: true
          grafanaDashboard:
            enabled: false  # @todo
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
