---
# yaml-language-server: $schema=../../../../schemas/cluster-values.json
applications:
  external-secrets:
    namespace: external-secrets
    path: kubernetes/apps/external-secrets/external-secrets
    psp: restricted
    ignoreDifferences: |
      - group: ""
        kind: Secret
        name: bitwarden-tls-certs
        jsonPointers:
          - "/data"
