---
# {{ if .Values.installSecretStore }}
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretsmanager
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.eu
      identityURL: https://identity.bitwarden.eu
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
            namespace: "{{ .Release.Namespace }}"
      bitwardenServerSDKURL: "https://bitwarden-sdk-server.{{ .Release.Namespace }}.svc.cluster.local:9998"
      caProvider:
        key: ca.crt
        name: bitwarden-tls-certs
        namespace: "{{ .Release.Namespace }}"
        type: Secret
      organizationID: 6d56fa67-67e1-4697-9d7f-b2ad00d31d5d
      projectID: ecbaa211-ce8b-49e7-ba23-b2ad00d36ae1
# {{ end }}
