---
# yamllint disable rule:line-length
# {{- $ca := genCA "O=external-secrets.io,CN=cert-manager-bitwarden-tls" 36500 -}}
# {{- $cert := genSignedCert "vault" (list "127.0.0.1") (list "localhost" (print "bitwarden-sdk-server." .Release.Namespace ".svc.cluster.local")) 36500 $ca }}
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.33.0/secret-v1.json
# yamllint enable rule:line-length
apiVersion: v1
kind: Secret
metadata:
  name: bitwarden-tls-certs
type: kubernetes.io/tls
data:
  ca.crt: "{{ $ca.Cert | b64enc }}"
  tls.key: "{{ $cert.Key | b64enc }}"
  tls.crt: "{{ $cert.Cert | b64enc }}"
---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretsmanager
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.eu
      identityURL: https://identity.bitwarden.eu
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
            namespace: "{{ .Release.Namespace }}"
      bitwardenServerSDKURL: "https://bitwarden-sdk-server.{{ .Release.Namespace }}.svc.cluster.local:9998"
      caBundle: "{{ $ca.Cert | b64enc }}"
      organizationID: 6d56fa67-67e1-4697-9d7f-b2ad00d31d5d
      projectID: ecbaa211-ce8b-49e7-ba23-b2ad00d36ae1
