---
argo-cd:
  nameOverride: argo-cd
  global:
    deploymentStrategy:
      type: RollingUpdate
    securityContext:
      runAsNonRoot: true
      runAsUser: 999
      runAsGroup: 999
      seccompProfile:
        type: RuntimeDefault
  configs:
    params:
      # by default argocd handles SSL termination on its own, which breaks TLS termination on nginx,
      # causing infinite loop
      "server.insecure": true
    repositories:
      deedee-ops-home-ops:
        name: home-ops
        type: git
        url: https://github.com/ajgon/home-test.git
    cm:
      # this customization make sync-waves work properly
      resource.customizations: |
        argoproj.io/Application:
          health.lua: |
            hs = {}
            hs.status = "Progressing"
            hs.message = ""
            if obj.status ~= nil then
              if obj.status.health ~= nil then
                hs.status = obj.status.health.status
                if obj.status.health.message ~= nil then
                  hs.message = obj.status.health.message
                end
              end
            end
            return hs
      resource.exclusions: |
        - apiGroups:
          - cilium.io
          kinds:
          - CiliumIdentity
          clusters:
          - "*"
        - apiGroups:
          - actions.github.com
          kinds:
          - AutoscalingListener
          clusters:
          - "*"

    rbac:
      policy.csv: g, lldap_admin, role:admin

  controller:
    replicas: 2
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  dex:
    enabled: false

  notifications:
    enabled: false

  server:
    replicas: 2
    ingress:
      enabled: true
      ingressClassName: internal
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  repoServer:
    replicas: 2
    podLabels:
      # for downloading helm charts from various sources
      egress/enabled: "true"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  applicationSet:
    replicas: 2
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  redis:
    enabled: true
    serviceAccount:
      create: true
    exporter:
      enabled: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
