{{ range $app, $applications := .Values.applications }}
{{ if has $app $.Values.apps }}
{{ range $application := $applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: '{{ $application.name }}'
  namespace: argocd
spec:
  destination:
    namespace: '{{ $application.namespace }}'
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/ajgon/home-test.git'
    targetRevision: 'master'
    path: '{{ $application.path }}'
    {{- if $application.helmValues }}
    helm:
      values: |
        {{- tpl $application.helmValues $ | nindent 8 }}
    {{- else }}
    helm: {}
    {{- end }}
  syncPolicy:
    automated:
      prune: true
    {{- if $application.psp }}
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: {{ $application.psp }}
        pod-security.kubernetes.io/audit: {{ $application.psp }}
        pod-security.kubernetes.io/warn: {{ $application.psp }}
    {{- end }}
{{- end}}
{{- end}}
{{- end}}
