{{ range $app, $applications := .Values.applications }}
{{ if has $app $.Values.apps }}
{{ range $application := $applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: '{{ $application.name }}'
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: '{{ $application.namespace }}'
  source:
    repoURL: 'https://github.com/ajgon/home-test.git'
    targetRevision: 'master'
    path: '{{ $application.path }}'
    helm:
      values: |
        {{- if $application.helmValues }}
        {{- tpl $application.helmValues $ | nindent 8 }}
        {{- end }}
  project: default
{{- end}}
{{- end}}
{{- end}}
