# {{ if false }}
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumclusterwidenetworkpolicy_v2.json
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: disable-egress
specs:
  - endpointSelector:
      matchExpressions:
        - key: egress/enabled
          operator: NotIn
          values:
            - "true"
    egress:
      - toCIDRSet:
          # sometimes cilium mistakes svc/pod CIDR as world, so let's allow it explicitly
          - cidr: 172.30.0.0/15
      - toEntities:
          - cluster
      - toEndpoints:
          - matchLabels:
              io.kubernetes.pod.namespace: kube-system
              k8s-app: kube-dns
        toPorts:
          - ports:
              - port: "53"
                protocol: ANY
            rules:
              dns:
                - matchPattern: "*"
  - endpointSelector:
      matchLabels:
        k8s-app: kube-dns
    egress:
      - toEntities:
          - world
        toPorts:
          - ports:
              - port: "53"
                protocol: ANY
            rules:
              dns:
                - matchPattern: "*"
# {{ end }}
